In [2]:
'''
2022.10.21, checking data for event detection
Models:
    1) FinEvent
    2) KPGNN
'''

'\n2022.10.21, checking data for event detection\nModels:\n    1) FinEvent\n    2) KPGNN\n'

In [3]:
import numpy as np
import pandas as pd

import os
project_path = os.getcwd()

In [4]:
project_path

'D:\\PycharmProjects\\GNN_Event_Detection_models'

## FinEvet data

### offline data

In [5]:
# Twitter offline data for FinEvent model
offline_data = '/data/FinEvent_datasets/offline/0'

In [6]:
data_features = np.load(project_path + offline_data + '/features.npy')
data_labels = np.load(project_path + offline_data + '/labels.npy')

In [7]:
data_features.shape

(68841, 300)

In [8]:
data_features

array([[-0.2108075 ,  0.20623374,  0.20069999, ..., -0.263     ,
         0.21215501,  0.190649  ],
       [-0.06414334,  0.16038734,  0.471691  , ..., -0.12185667,
         0.06794   ,  0.12017686],
       [-0.25564337,  0.06492691,  0.30455333, ..., -0.35371998,
         0.34504333,  0.15217233],
       ...,
       [-0.23498434, -0.06000866,  0.27791   , ...,  0.03108733,
        -0.19636732, -0.08902135],
       [-0.19697833,  0.17932083, -0.18321826, ...,  0.05813325,
        -0.02271575,  0.12811857],
       [-0.0559687 ,  0.14717391, -0.07961421, ..., -0.13795723,
         0.05610847,  0.09389253]], dtype=float32)

In [9]:
data_labels.shape

(68841,)

In [10]:
data_labels

array([394, 394, 394, ...,  52, 197, 430], dtype=int64)

### incremental data

In [11]:
# Twitter incremental data

In [12]:
incremental_data = '/data/FinEvent_datasets/incremental'

In [13]:
data_all_graph_mins = np.load(project_path + incremental_data + '/all_graph_mins.npy')
data_data_split = np.load(project_path + incremental_data + '/data_split.npy')

In [14]:
data_all_graph_mins.shape

(22,)

In [15]:
data_all_graph_mins

array([0.88943383, 0.16785372, 0.00560299, 0.00812201, 0.00907635,
       0.00749143, 0.00390392, 0.06602791, 0.00678952, 0.00465628,
       0.00325728, 0.00327895, 0.02269816, 0.00928863, 0.01886542,
       0.01287993, 0.002161  , 0.01506681, 0.00800496, 0.00414097,
       0.00237813, 0.01290204])

In [16]:
data_data_split.shape

(22,)

#### day 0

In [20]:
data_features = np.load(project_path + incremental_data + '/0/features.npy')
data_labels = np.load(project_path + incremental_data + '/0/labels.npy')
# data_relation_config = np.load(project_path + incremental_data + '/0/relation_config.npy', allow_pickle=True)

In [21]:
data_features.shape

(20254, 300)

In [22]:
data_features

array([[-0.2108075 ,  0.20623374,  0.20069999, ..., -0.263     ,
         0.21215501,  0.190649  ],
       [-0.06414334,  0.16038734,  0.471691  , ..., -0.12185667,
         0.06794   ,  0.12017686],
       [-0.25564337,  0.06492691,  0.30455333, ..., -0.35371998,
         0.34504333,  0.15217233],
       ...,
       [-0.0553655 ,  0.05928   , -0.10435   , ...,  0.01208425,
        -0.18419175, -0.11138435],
       [-0.02057833, -0.01771078, -0.07201657, ...,  0.12110816,
        -0.31362444, -0.00799999],
       [-0.166718  ,  0.1659406 , -0.02848601, ..., -0.15238741,
        -0.195202  ,  0.10067419]], dtype=float32)

In [23]:
data_labels.shape

(20254,)

In [24]:
np.unique(data_labels)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  18,  19,  20,  21,
        22,  23,  24,  27,  28,  71,  75,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 148, 192,
       238, 239, 240, 241, 242, 243, 244, 245, 246, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 310, 311, 312, 313, 314,
       315, 316, 317, 318, 320, 321, 322, 323, 324, 325, 326, 327, 328,
       346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358,
       359, 360, 361, 362, 363, 364, 365, 366, 380, 381, 382, 383, 384,
       385, 386, 394, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475,
       476, 477, 478, 479, 480, 487, 500, 501, 502, 503, 504, 505],
      dtype=int64)

In [25]:
data_labels

array([394, 394, 394, ...,   8, 351,  20], dtype=int64)

#### day 1

In [26]:
data_features = np.load(project_path + incremental_data + '/1/features.npy')
data_labels = np.load(project_path + incremental_data + '/1/labels.npy')
# data_relation_config = np.load(project_path + incremental_data + '/1/relation_config.npy', allow_pickle=True)

In [27]:
data_features.shape

(8722, 300)

In [28]:
data_features

array([[-0.1876805 ,  0.060796  , -0.18039191, ...,  0.0186169 ,
         0.1161634 , -0.071475  ],
       [-0.0062081 ,  0.05227879, -0.02977721, ..., -0.0182999 ,
        -0.31581932,  0.1304561 ],
       [ 0.07530945,  0.14353155, -0.2836156 , ..., -0.12168166,
         0.37752703, -0.03327982],
       ...,
       [ 0.11428875, -0.00918162, -0.16528925, ...,  0.19711208,
        -0.20216438, -0.07916175],
       [ 0.12064295, -0.0106019 ,  0.12542793, ..., -0.07570857,
        -0.01984036, -0.17617427],
       [-0.21470843, -0.02862857,  0.31913716, ..., -0.00729572,
        -0.04512414,  0.09993502]], dtype=float32)

In [29]:
data_labels.shape

(8722,)

In [30]:
data_labels

array([  8,  20,   8, ..., 196, 349,  28], dtype=int64)

## KPGNN data

In [31]:
# https://github.com/RingBDStack/KPGNN/blob/main/datasets/data_usage.md

### Twitter data

In [36]:
project_path + twitter_data_path + '/68841_tweets_multiclasses_filtered_0722_part1.npy'

'D:\\PycharmProjects\\GNN_Event_Detection_models/data/KPGNN datasets/Twitter/68841_tweets_multiclasses_filtered_0722_part1.npy'

In [37]:
twitter_data_path = '/data/KPGNN datasets/Twitter'
twitter_data_part1 = np.load(project_path + twitter_data_path + '/68841_tweets_multiclasses_filtered_0722_part1.npy', allow_pickle=True)
twitter_data_part2 = np.load(project_path + twitter_data_path + '/68841_tweets_multiclasses_filtered_0722_part2.npy', allow_pickle=True)

In [43]:
twitter_data_part1

array([[0, 256292946331181056,
        'Nobel prize in literature to be announced http://t.co/qxlEqdl3',
        ..., list(['literature', 'Nobel', 'prize', 'announce']),
        list(['literature', 'nobel', 'prize', 'announce']), list([])],
       [0, 256333064467279872,
        "“@marvicleonen: Is it true that UP won UAAP basketball?” -- Next year, Dean. Sure na 'yan!",
        ...,
        list(['Dean', 'Sure', 'year', 'yan', 'na', '"', 'basketball', 'true', 'next', 'UAAP']),
        list(['dean', 'sure', 'year', 'yan', 'na', 'basketball', 'true', 'next', 'uaap']),
        list([])],
       [0, 256334302034399232,
        'Congrats, Ateneo! Last na yan ha. Season 76 will be different. ☺',
        ...,
        list(['yan', '☺', 'na', 'ha', 'different', 'last', 'Ateneo', 'congrat', 'Season']),
        list(['yan', 'na', 'ha', 'different', 'last', 'ateneo', 'congrat', 'season']),
        list([])],
       ...,
       [1, 256569208165502976,
        "Doh! Hit em with the #sarahpalin...th

In [42]:
# 合并数据集
twitter_data = np.concatenate((twitter_data_part1, twitter_data_part2), axis=0)
print('Loaded Twitter data')

Loaded Twitter data


In [44]:
df_twitter = pd.DataFrame(data=twitter_data, 
                          columns=['event_id', 'tweet_id', 'text', 'user_id', 'created_at', 'user_loc', 'place_type',
                                  'place_full_name', 'place_country_code', 'hashtags', 'user_mentions', 'image_urls', 'entities',
                                  'words', 'filtered_words', 'sampled_words'])

In [48]:
df_twitter.head(5)

event_id            tweet_id  \
0        0  256292946331181056   
1        0  256333064467279872   
2        0  256334302034399232   
3        0  256335853738160128   
4        0  256346272506712064   

                                                text    user_id  \
0  Nobel prize in literature to be announced http...   47667947   
1  “@marvicleonen: Is it true that UP won UAAP ba...   67518107   
2  Congrats, Ateneo! Last na yan ha. Season 76 wi...   97449266   
3  "@SMARTPromos: SMART never wants you to be lef...  405138197   
4  CCTV invite hints at Nobel literature prize fo...  197326414   

           created_at           user_loc place_type place_full_name  \
0 2012-10-11 07:19:34    Munich, Germany                              
1 2012-10-11 09:58:59        Philippines                              
2 2012-10-11 10:03:54                                                 
3 2012-10-11 10:10:04  Lost in Dreamland                              
4 2012-10-11 10:51:28      Taiwan(R.O.C)                              

  place_country_code hashtags user_mentions image_urls  \
0                          []            []         []   
1                          []    [28775032]         []   
2                          []            []         []   
3                          []   [106915372]         []   
4                          []            []         []   

                                            entities  \
0                                                 []   
1     [(UP, ORG), (Next year, DATE), (Dean, PERSON)]   
2            [(Ateneo, PERSON), (Season 76, PERSON)]   
3                           [(BIG, ORG), (BIG, ORG)]   
4  [(CCTV, ORG), (Nobel, WORK_OF_ART), (Mo Yan, P...   

                                               words  \
0               [literature, Nobel, prize, announce]   
1  [Dean, Sure, year, yan, na, ", basketball, tru...   
2  [yan, ☺, na, ha, different, last, Ateneo, cong...   
3  [never, s, yan, next, na, thing, Ano, leave, t...   
4  [invite, prize, Yan, literature, hint, CCTV, N...   

                                      filtered_words sampled_words  
0               [literature, nobel, prize, announce]            []  
1  [dean, sure, year, yan, na, basketball, true, ...            []  
2  [yan, na, ha, different, last, ateneo, congrat...            []  
3  [never, yan, next, na, thing, ano, leave, that...            []  
4  [invite, prize, yan, literature, hint, cctv, n...            []

In [45]:
print('Data converted to dataframe')
print(df_twitter.shape)
print(df_twitter.head(10))

Data converted to dataframe
(68841, 16)
  event_id            tweet_id  \
0        0  256292946331181056   
1        0  256333064467279872   
2        0  256334302034399232   
3        0  256335853738160128   
4        0  256346272506712064   
5        0  256346650132508673   
6        0  256349023773024256   
7        0  256349178991624192   
8        0  256349191863943168   
9        0  256349325876137984   

                                                text    user_id  \
0  Nobel prize in literature to be announced http...   47667947   
1  “@marvicleonen: Is it true that UP won UAAP ba...   67518107   
2  Congrats, Ateneo! Last na yan ha. Season 76 wi...   97449266   
3  "@SMARTPromos: SMART never wants you to be lef...  405138197   
4  CCTV invite hints at Nobel literature prize fo...  197326414   
5  mjzone58: SIR HINDI BYAHE YAN. WALA TALAGANG P...  397051720   
6  BREAKING: The 2012 Nobel Prize for Literature ...    7424642   
7  "@GuardianBooks: And the #Nobel prize for lite